spring.application.name=TBF_Rebecca_Sacarescu
spring.datasource.url=jdbc:postgresql://localhost:5432/TBF
spring.datasource.username=postgres
spring.datasource.password=rebecca

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=VGhpcy1pcy1hLWJhc2U2NC1lbmNvZGVkLXNlY3JldC1rZXktZm9yLVRCRg==
security.jwt.expiration-ms=3600000

server.port=8088
